version: "3.8"

services:
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations api
            python manage.py migrate
            python manage.py createtestuser
            python manage.py loaddata library/fixtures/type_transactions.json
            python manage.py test
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: