version: "3.9"

services:
  web:
    build: ""
    command: >
      sh -c "python manage.py makemigrations api
            python manage.py migrate
            python manage.py createsuperuser
            python manage.py loaddata api/fixtures/type_transactions.json
            python manage.py test
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000

    environment:
      - DB_HOST=DB
      - DB_NAME=db_financial
      - DB_USER=financial
      - DB_PASS=12345
      - DB_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=db_financial
      - POSTGRES_USER=financial
      - POSTGRES_PASSWORD=12345

    ports:
      - 5433:5432

    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: